version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"
    # For pnpm with a catalog, we want to update the versions in the manifest files.
    versioning-strategy: increase
    groups:
      # Group all dependencies into a single PR.
      all-deps:
        patterns:
          - "*"
